content: https://github.com/hirenoble/hlx-api.git#master
static: https://github.com/hirenoble/hlx-api.git#master
staticRoot: /webroot
directoryIndex: index.html

#strains:
#  default:
#    code:
#    content: https://github.com/hirenoble/hlx-api.git#master
#    static: https://github.com/hirenoble/hlx-api.git#master
#    staticRoot: /webroot
#    directoryIndex: index.html